### ISSUE TITLE
Use github actions to publish to npm

### ISSUE THREAD

**Issue by psykzz** [contentstack/gatsby-source-contentstack#114]
Just wanted to throw a suggestion to publish new version of the app via github actions.

This could help elevate the issue raised in #113, but also reduce the burden on maintainers to run the release process.

An example workflow could be something like

```
name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x' 
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      # This already includes a build step, but we can also be more explicit if we want.
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

````

If we wanted to go with this approach, we'd just need a maintainer to add the NPM token into the repo secrets.
I can attach a PR for the publish workflow, if required.
